[".config/alacritty/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/alacritty/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
  include = ["*/*.yml"]

{{ range .catppuccinFlavoursTitleCase }}
[".config/bat/themes/Catppuccin {{ . }}.tmTheme"]
  type = "archive-file"
  url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
  path = "themes/Catppuccin {{ . }}.tmTheme"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}


{{ range .catppuccinFlavours }}
[".config/btop/themes/catppuccin_{{ . }}.theme"]
  type = "archive-file"
  url = "https://github.com/catppuccin/btop/archive/main.tar.gz"
  path = "themes/catppuccin_{{ . }}.theme"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}


{{ range .catppuccinFlavours }}
{{ if ne $.chezmoi.os "windows" }}
[".config/discord/themes/catppuccin/{{ . }}.theme.css"]
{{ else }}
["AppData/Roaming/discord/themes/catppuccin/{{ . }}.theme.css"]
{{ end }}
  type = "archive-file"
  url = "https://github.com/catppuccin/discord/archive/main.tar.gz"
  path = "themes/mocha.theme.css"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

{{ range .catppuccinFlavoursTitleCase }}
[".config/fish/themes/Catppuccin {{ . }}.theme"]
  type = "archive-file"
  url = "https://github.com/catppuccin/fish/archive/main.tar.gz"
  path = "themes/Catppuccin {{ . }}.theme"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

{{ range .catppuccinFlavours }}
[".config/gitui/{{ . }}.ron"]
  type = "archive-file"
  url = "https://github.com/catppuccin/gitui/archive/main.tar.gz"
  path = "theme/{{ . }}.ron"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

{{ range .catppuccinFlavours }}
[".config/fsh/catppuccin-{{ . }}.ini"]
  type = "archive-file"
  url = "https://github.com/catppuccin/zsh-fsh/archive/main.tar.gz"
  path = "themes/catppuccin-{{ . }}.ini"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{end}}

{{ range .catppuccinFlavours }}
[".config/gitui/catppuccin-{{ . }}.ini"]
  type = "archive-file"
  url = "https://github.com/catppuccin/zsh-fsh/archive/main.tar.gz"
  path = "themes/catppuccin-{{ . }}.ini"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{end}}

{{ range .catppuccinFlavours }}
[".config/helix/themes/catppuccin_{{ . }}.toml"]
  type = "archive-file"
  url = "https://github.com/catppuccin/helix/archive/main.tar.gz"
  path = "themes/default/catppuccin_{{ . }}.toml"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

{{ range .catppuccinFlavours }}
[".config/hypr/themes/catppuccin-{{ . }}.conf"]
  type = "archive-file"
  url = "https://github.com/catppuccin/hyprland/archive/main.tar.gz"
  path = "themes/{{ . }}.conf"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

{{ range .catppuccinFlavours }}
[".config/k9s/skins/catppuccin-{{ . }}.yaml"]
  type = "archive-file"
  url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
  path = "dist/catppuccin-{{ . }}.yaml"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".config/k9s/skins/catppuccin-{{ . }}-transparent.yaml"]
  type = "archive-file"
  url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
  path = "dist/catppuccin-{{ . }}-transparent.yaml"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

{{ range .catppuccinFlavours }}
[".config/kitty/themes/{{ . }}.conf"]
  type = "archive-file"
  url = "https://github.com/catppuccin/kitty/archive/main.tar.gz"
  path = "themes/{{ . }}.conf"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

{{ range .catppuccinFlavoursTitleCase }}
[".config/qt5ct/colors/Catppuccin-{{ . }}.conf"]
  type = "archive-file"
  url = "https://github.com/catppuccin/qt5ct/archive/main.tar.gz"
  path = "themes/Catppuccin-{{ . }}.conf"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

{{- if ne $.chezmoi.os "windows" }}
[".config/spicetify/Themes/catppuccin"]
{{ else }}
["AppData/Roaming/spicetify/Themes/catppuccin"]
{{ end }}
  type = "archive"
  url = "https://github.com/catppuccin/spicetify/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "1h"
  include = ["*/catppuccin/**"]

# Now maintined in Zellij
#[".config/zellij/themes/catppuccin.yaml"]
#  type = "archive-file"
#  url = "https://github.com/catppuccin/zellij/archive/main.tar.gz"
#  path = "catppuccin.yaml"
#  exact = true
#  stripComponents = 1
#  refreshPeriod = "1h"

{{ range .catppuccinFlavours }}
[".fleet/themes/catppuccin-{{ . }}.json"]
  type = "archive-file"
  url = "https://github.com/kkrypt0nn/jetbrains-fleet/archive/main.tar.gz"
  path = "themes/catppuccin-{{ . }}.json"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

{{ range .catppuccinFlavours }}
[".local/share/gedit/styles/catppuccin-{{ . }}.xml"]
  type = "archive-file"
  url = "https://github.com/catppuccin/gedit/archive/main.tar.gz"
  path = "themes/catppuccin-{{ . }}.xml"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

[".local/share/icons/{{ .catppuccinCursorTheme }}"]
  type = "archive"
  url = "https://github.com/catppuccin/cursors/releases/latest/download/{{ .catppuccinCursorTheme }}.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".local/share/icons/Papirus"]
  type = "archive"
  url = "https://github.com/catppuccin/papirus-folders/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "1h"
  include = ["*/src/**"]


{{ range .catppuccinFlavoursTitleCase }}
[".local/share/konsole/Catppuccin-{{ . }}.colorscheme"]
type = "archive-file"
  url = "https://github.com/catppuccin/konsole/archive/main.tar.gz"
  path = "Catppuccin-{{ . }}.colorscheme"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
{{ end }}

[".local/share/catppuccin/gtk"]
  type = "archive"
  url = "https://github.com/catppuccin/gtk/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".local/share/mc/skins/catppuccin.ini"]
  type = "archive-file"
  url = "https://github.com/catppuccin/mc/archive/main.tar.gz"
  path = "catppuccin.ini"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".local/share/powershell/Modules/Catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/powershell/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

{{- if ne $.chezmoi.os "windows" }}
[".themes/{{ .catppuccinGtkTheme }}/"]
  type = "archive"
  url = "https://github.com/catppuccin/gtk/releases/latest/download/{{ .catppuccinGtkTheme }}.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
  include = ["{{ .catppuccinGtkTheme }}/**"]
{{ end }}

# {{ if eq $.chezmoi.os "windows" }}
  {{ range .catppuccinFlavours }}
  ["Appdata/Roaming/Notepad++/themes/catppuccin-{{ . }}.xml"]
    type = "archive-file"
    url = "https://github.com/catppuccin/notepad-plus-plus/archive/main.tar.gz"
    path = "catppuccin-{{ . }}.xml"
    exact = true
    stripComponents = 1
    refreshPeriod = "1h"
  {{ end }}
# {{ end }}

{{ if eq $.chezmoi.os "windows" }}
  {{ range .catppuccinFlavoursTitleCase }}
  ["AppData/Roaming/FlowLauncher/Themes/Catppuccin {{ . }}.xaml"]
    type = "archive-file"
    url = "https://github.com/catppuccin/flow-launcher/archive/main.tar.gz"
    path = "themes/Catppuccin {{ . }}.xaml"
    exact = true
    stripComponents = 1
    refreshPeriod = "1h"
  {{ end }}
{{ end }}
