{{- if ne .chezmoi.os "windows" }}

[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".oh-my-zsh/custom/plugins/fast-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".oh-my-zsh/custom/plugins/zsh-vi-mode"]
  type = "archive"
  url = "https://github.com/jeffreytse/zsh-vi-mode/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

{{ $powerlevel10kVersion := (gitHubLatestRelease "romkatv/powerlevel10k").TagName }}
[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/{{ $powerlevel10kVersion }}.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

{{ end }}
