[".local/share/zellij/plugins/multitask.wasm"]
  type = "file"
  url = "https://github.com/imsnif/multitask/releases/latest/download/multitask.wasm"
  refreshPeriod = "1h"

[".local/share/zellij/plugins/zellij-autolock.wasm"]
  type = "file"
  url = "https://github.com/fresh2dev/zellij-autolock/releases/latest/download/zellij-autolock.wasm"
  refreshPeriod = "1h"

[".local/share/zellij/plugins/zjstatus.wasm"]
  type = "file"
  url = "https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm"
  refreshPeriod = "1h"

