[".config/alacritty/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/alacritty/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"
  include = ["*/*.yml"]

{{ range .catppuccinFlavours }}
[".config/bat/themes/Catppuccin-{{ . }}.tmTheme"]
  type = "file"
  url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-main/Catppuccin-{{ . }}.tmTheme"]
{{ end }}

{{ range .catppuccinFlavours }}
[".config/btop/themes/catppuccin_{{ . }}.theme"]
  type = "file"
  url = "https://github.com/catppuccin/btop/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "btop-main/themes/catppuccin_{{ . }}.theme"]
{{ end }}

{{ range .catppuccinFlavours }}
[".config/foot/themes/catppuccin-{{ . }}.conf"]
  type = "file"
  url = "https://github.com/catppuccin/foot/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "foot-main/catppuccin-{{ . }}.conf"]
{{ end }}

{{ range .catppuccinFlavours }}
[".config/hypr/themes/catppuccin-{{ . }}.conf"]
  type = "file"
  url = "https://github.com/catppuccin/hyprland/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "hyprland-main/themes/{{ . }}.conf"]
{{ end }}

[".config/k9s/skin.yml"]
  type = "file"
  url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "k9s-main/dist/mocha.yml"]

{{ range .catppuccinFlavours }}
[".config/kitty/themes/{{ . }}.conf"]
  type = "file"
  url = "https://github.com/catppuccin/kitty/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "kitty-main/themes/{{ . }}.conf"]
{{ end }}

[".config/nvim"]
  type = "archive"
  url = "https://github.com/AstroNvim/AstroNvim/archive/main.tar.gz"
  exact = true
  stripComponents =1
  refreshPeriod = "1h"

{{ range .catppuccinFlavoursTitleCase }}
[".config/qt5ct/colors/Catppuccin-{{ . }}.conf"]
  type = "file"
  url = "https://github.com/catppuccin/qt5ct/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "qt5ct-main/themes/Catppuccin-{{ . }}.conf"]
{{ end }}

{{ range .catppuccinFlavoursTitleCase }}
[".config/qt6ct/colors/Catppuccin-{{ . }}.conf"]
  type = "file"
  url = "https://github.com/catppuccin/qt5ct/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "qt5ct-main/themes/Catppuccin-{{ . }}.conf"]
{{ end }}

{{ range .catppuccinFlavours }}
[".fleet/themes/catppuccin-{{ . }}.json"]
  type = "file"
  url = "https://github.com/kkrypt0nn/jetbrains-fleet/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "jetbrains-fleet-main/themes/catppuccin-{{ . }}.json"]
{{ end }}

[".local/bin/zsweep"]
  type = "file"
  url = "https://github.com/psprint/zsh-sweep/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "zsh-sweep-master/bin/zsweep"]

[".local/share/catppuccin/gtk"]
  type = "archive"
  url = "https://github.com/catppuccin/gtk/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

{{ range .catppuccinFlavours }}
[".local/share/gedit/styles/catppuccin-{{ . }}.xml"]
  type = "file"
  url = "https://github.com/catppuccin/gedit/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "gedit-main/themes/catppuccin-{{ . }}.xml"]
{{ end }}

[".local/share/lunarvim/lvim/"]
  type = "archive"
  url = "https://github.com/LunarVim/LunarVim/archive/release-1.3/neovim-0.9.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".local/share/mc/skins/catppuccin.ini"]
  type = "file"
  url = "https://github.com/catppuccin/mc/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "mc-main/catppuccin.ini"]

[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/v1.19.0.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".pyenv"]
  type = "archive"
  url = "https://github.com/pyenv/pyenv/archive/refs/tags/v2.3.21.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".pyenv/plugins/pyenv-virtualenv"]
  type = "archive"
  url = "https://github.com/pyenv/pyenv-virtualenv/archive/refs/tags/v1.2.1.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

[".tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "1h"

{{ range .catppuccinGtkThemes }}
[".themes/{{ . }}"]
  type = "archive"
  url = "https://github.com/catppuccin/gtk/releases/download/v0.6.0/{{ . }}.zip"
  exact = true
  refreshPeriod = "1h"
{{ end }}