
{{ range .catppuccinFlavours }}
[".config/bat/themes/Catppuccin-{{ . }}.tmTheme"]
  type = "file"
  url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-main/Catppuccin-{{ . }}.tmTheme"]
{{ end }}

[".local/share/lunarvim/lvim/"]
  type = "archive"
  url = "https://github.com/LunarVim/LunarVim/archive/release-1.3/neovim-0.9.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
  exact = true
  stripComponents = 1

