catppuccinCursorTheme = 'Catppuccin-Mocha-Light-Cursors'
catppuccinFlavours = ['frappe', 'latte', 'macchiato', 'mocha']
catppuccinFlavoursTitleCase = ['Frappe', 'Latte', 'Macchiato', 'Mocha']
catppuccinGtkTheme = 'Catppuccin-Mocha-Standard-Blue-Dark'
