[".config/alacritty/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/alacritty/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/*.yml"]

{{ range .catppuccinFlavours }}
[".config/bat/themes/Catppuccin-{{ . }}.tmTheme"]
  type = "file"
  url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-main/Catppuccin-{{ . }}.tmTheme"]
{{ end }}

[".config/k9s/skin.yml"]
  type = "file"
  url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "k9s-main/dist/mocha.yml"]

[".config/nvim"]
  type = "archive"
  url = "https://github.com/AstroNvim/AstroNvim/archive/main.tar.gz"
  exact = true
  stripComponents =1
  refreshPeriod = "168h"

{{ range .catppuccinFlavours }}
[".fleet/themes/catppuccin-{{ . }}.json"]
  type = "file"
  url = "https://github.com/kkrypt0nn/jetbrains-fleet/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "jetbrains-fleet-main/themes/catppuccin-{{ . }}.json"]
{{ end }}

[".local/share/lunarvim/lvim/"]
  type = "archive"
  url = "https://github.com/LunarVim/LunarVim/archive/release-1.3/neovim-0.9.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".pyenv"]
  type = "archive"
  url = "https://github.com/pyenv/pyenv/archive/refs/tags/v2.3.17.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".pyenv/plugins/pyenv-virtualenv"]
  type = "archive"
  url = "https://github.com/pyenv/pyenv-virtualenv/archive/refs/tags/v1.2.1.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

