return {
  {
    "Astronvim/astrocommunity",
    -- dev = true,
  },
  { import = "user.plugins.community.bars-and-lines" },
  { import = "user.plugins.community.code-runner" },
  { import = "user.plugins.community.color" },
  { import = "user.plugins.community.colorscheme" },
  { import = "user.plugins.community.completion" },
  { import = "user.plugins.community.debugging" },
  { import = "user.plugins.community.diagnostics" },
  { import = "user.plugins.community.editing-support" },
  { import = "user.plugins.community.fuzzy-finder" },
  { import = "user.plugins.community.indent" },
  { import = "user.plugins.community.lsp" },
  { import = "user.plugins.community.markdown-and-latex" },
  { import = "user.plugins.community.motion" },
  { import = "user.plugins.community.note-taking" },
  { import = "user.plugins.community.pack" },
  { import = "user.plugins.community.project" },
  { import = "user.plugins.community.programming-language-support" },
  { import = "user.plugins.community.register" },
  { import = "user.plugins.community.remote-development" },
  { import = "user.plugins.community.scrolling" },
  { import = "user.plugins.community.syntax" },
  { import = "user.plugins.community.terminal-integration" },
  { import = "user.plugins.community.test" },
  { import = "user.plugins.community.utility" },
  { import = "user.plugins.community.workflow" },
}
