[env]
'_'.python.venv = { path = ".venv", create = true }

[tools]
lua = "5.1.5"
node = "22"
"npm:neovim" = "latest"
perl = "latest"
pnpm = "latest"
poetry = { version = 'latest', pyproject = 'pyproject.toml' }
python = "3.12"
ruby = "3.3"
