[settings]
python.uv_venv_create_args = ['--seed']
python.uv_venv_auto = true

[tools]
"gem:neovim" = "latest"
lua = "5.1.5"
node = "22"
perl = "latest"
pnpm = "latest"
poetry = { version = 'latest', pyproject = 'pyproject.toml' }
python = "3.12"
ruby = "latest"
uv = "latest"

[tasks.installPerlModule]
description = "Install Perl Module"
run = "cpanm -n Neovim::Ext"
