[env]
'_'.python.venv = { path = ".venv", create = true }

[tools]
lua = "latest"
node = "lts"
"npm:neovim" = "latest"
perl = "latest"
poetry = { version = 'latest', pyproject = 'pyproject.toml' }
python = "latest"
ruby = "latest"
yarn = "latest"
