[tools]
bottom = "latest"
gdu = "latest"
"gem:neovim" = "latest"
lazygit = "latest"
lua = "5.1"
node = "lts"
"npm:neovim" = "latest"
perl = "latest"
"pipx:pynvim" = "latest"
python = "latest"
rg = "latest"

[tasks.installPerlModule]
description = "Install Perl Module"
run = "cpanm -n Neovim::Ext"
